version: '3.9'

services:

  #php/laravel
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./laravel_src:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    depends_on:
      - db

  #nginx
  web:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel_src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: bind
        source: ./docker/mysql/data_store
        target: /var/lib/mysql
    ports:
      - "3306:3306"
